// var y=2.25;
// var x=Math.abs(y);
// document.write("value: "+y);
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Abs: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);
// var x=Math.pow(-y);
// document.write("<br/>");
// document.write("value: "+(-y));
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Abs: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);