var y=71.978889000000000000000000;
var x=Math.ceil(y);
document.write("value: "+y);
document.write("<br/>");
document.write("Type: "+typeof y);
document.write("<br/>");
document.write("value: "+x);
document.write("<br/>");
document.write("Type: "+typeof x);
var x=Math.ceil(-y);
document.write("<br/>");
document.write("value: "+(-y));
document.write("<br/>");
document.write("Type: "+typeof y);
document.write("<br/>");
document.write("value: "+x);
document.write("<br/>");
document.write("Type: "+typeof x);