var date = new Date();
document.write(date);
document.write("<br/>");
document.write(date.toDateString());
document.write("<br/>");
document.write(date.getDate());
document.write("<br/>");
document.write(date.getFullYear());
document.write("<br/>");
document.write(date.getHours());
document.write("<br/>");
document.write(date.getUTCHours());
document.write("<br/>");
document.write(date.getMonth());
document.write("<br/>");
document.write(date.getDay());
document.write("<br/>");
document.write(date.getMinutes());
document.write("<br/>");
document.write(date.getSeconds());
document.write("<br/>");
document.write(date.getMilliseconds());
document.write("<br/>");
date.setDate(12)
document.write(date);
document.write("<br/>");
date.setFullYear(2024)
document.write(date);
document.write("<br/>");
date.setHours(5)
document.write(date);
document.write("<br/>");
date.setMinutes(12)
document.write(date);
document.write("<br/>");
date.setSeconds(12)
document.write(date);
document.write("<br/>");
date.setMilliseconds(12)
document.write(date);
document.write("<br/>");
date.setTime(5)
document.write(date);
document.write("<br/>");

