// var y=71.978889000000000000000000;
// var x=Math.ceil(y);
// document.write("value: "+y);
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("value: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);
// var x=Math.ceil(-y);
// document.write("<br/>");
// document.write("value: "+(-y));
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("value: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);

// var y=71.978889000000000000000000;
// var x=Math.floor(y);
// document.write("value: "+y);
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("value: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);
// var x=Math.floor(-y);
// document.write("<br/>");
// document.write("value: "+(-y));
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("value: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);

// var y=71.5;
// var x=Math.round(y);
// document.write("value: "+y);
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("value: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);
// var x=Math.round(-y);
// document.write("<br/>");
// document.write("value: "+(-y));
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("value: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);

// var y=71.5;
// var x=Math.trunc(y);
// document.write("value: "+y);
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("value: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);
// var x=Math.round(-y);
// document.write("<br/>");
// document.write("value: "+(-y));
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("value: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);

// var y=71.5,z=80.5;
// var x=Math.max(y,z);
// document.write("value: "+y+" & "+z);
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Max: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);
// var x=Math.max(-y,-z);
// document.write("<br/>");
// document.write("value: "+(-y)+" & "+(-z));
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Max: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);

// var y=71.5,z=80.5;
// var x=Math.min(y,z);
// document.write("value: "+y+" & "+z);
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Min: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);
// var x=Math.min(-y,-z);
// document.write("<br/>");
// document.write("value: "+(-y)+" & "+(-z));
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Min: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);

// var y=64;
// var x=Math.sqrt(y);
// document.write("value: "+y);
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Sqrt: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);
// var x=Math.sqrt(-y);
// document.write("<br/>");
// document.write("value: "+(-y));
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Sqrt: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);

// var y=8;
// var x=Math.cbrt(y);
// document.write("value: "+y);
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Cbrt: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);
// var x=Math.cbrt(-y);
// document.write("<br/>");
// document.write("value: "+(-y));
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Cbrt: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);

// var y=2,z=3;
// var x=Math.pow(y,z);
// document.write("value: "+y+"^"+z);
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Pow: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);
// var x=Math.pow(-y,-z);
// document.write("<br/>");
// document.write("value: "+(-y)+"^"+(-z));
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Pow: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);

// var x=Math.random();
// document.write("Random value: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);
// var x=Math.random()*10;
// document.write("<br/>");
// document.write("Random value: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);
// var x=Math.random()*10+10;
// document.write("<br/>");
// document.write("Random value: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);

// var y=2.25;
// var x=Math.abs(y);
// document.write("value: "+y);
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Abs: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);
// var x=Math.pow(-y);
// document.write("<br/>");
// document.write("value: "+(-y));
// document.write("<br/>");
// document.write("Type: "+typeof y);
// document.write("<br/>");
// document.write("Abs: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);

// var x=Math.PI;
// document.write("Pi: "+x);
// document.write("<br/>");
// document.write("Type: "+typeof x);