var y=71.5,z=80.5;
var x=Math.max(y,z);
document.write("value: "+y+" & "+z);
document.write("<br/>");
document.write("Type: "+typeof y);
document.write("<br/>");
document.write("Max: "+x);
document.write("<br/>");
document.write("Type: "+typeof x);
var x=Math.max(-y,-z);
document.write("<br/>");
document.write("value: "+(-y)+" & "+(-z));
document.write("<br/>");
document.write("Type: "+typeof y);
document.write("<br/>");
document.write("Max: "+x);
document.write("<br/>");
document.write("Type: "+typeof x);